### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by nbwpuk** [mautic/mautic-helper-chrome-extension#1]
I sometime have an issue where I am unable to send an email from Gmail when I have selected to track in Mautic. Whilst debugging I have seen the following errors logged to the console when using the Chrome extension

`Uncaught TypeError: Cannot read property 'split' of undefined
    at hashCode (js/background.js:28)
    at js/background.js:84
    at XMLHttpRequest.h.onreadystatechange (xhr.js:3)`

**Comment by RCheesley** [comment]
Closing this issue due to lack of recent dialogue.
